version: '2.3'

volumes:
  dbv4

services:
  mongo:
    ports:
      - 27017:27017/tcp
    network_mode: "host"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    tty: true
    image: mongo:3.6.21-xenial
    container_name: "mongo"
    hostname: dbhost
    volumes:
      - dbv4:/data/db
    privileged: true
    restart: "no"
    command: mongod --auth
    #--storageEngine=mmapv1

  rabbitmq:
    ports:
      - 5672:5672/tcp
      - 15672:15672/tcp
    environment:
      RABBITMQ_ERLANG_COOKIE: "ONCLOUDTECHNOLOGIESSDNBHD"
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
      RABBITMQ_DEFAULT_VHOST: "/"
    network_mode: "host"
    tty: false
    image: rabbitmq:3-management
    labels:
      NAME: "rabbitmq"
    hostname: mqhost
    container_name: "rabbitmq"
    privileged: false
    restart: on-failure

  minio:
    ports:
      - 9000:9000/tcp
    environment:
      MINIO_ACCESS_KEY: AKIAJJHYQXINZ6KM4WHA
      MINIO_SECRET_KEY: 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
    command: server /data
    network_mode: "host"
    tty: false
    image: minio/minio
    labels:
      NAME: "minio"
    hostname: miniohost
    volumes:
      - C:\\minio\\data:/data
      - C:\\minio\\config:/root/.minio
    container_name: "minio"
    privileged: false
    restart: "no"

  gogs:
    ports:
      - 10022:22/tcp
      - 10080:3000/tcp
    network_mode: "host"
    tty: true
    image: gogs/gogs
    container_name: "gogs"
    hostname: gogshost
    volumes:
      - /var/gogs:/data
    privileged: false
    restart: "no"

  eureka:
    ports:
      - 8761:8761/tcp
    environment:
      spring.cloud.config.server.git.uri: http://office.oncloud.tech:10080/gogsadm/config-repo-dev
      spring.cloud.config.server.git.username: gogsadm
      spring.cloud.config.server.git.password: 0nCl0ud
      spring.profiles.active: default
      #      eureka.client.registerWithEureka: "true"
      eureka.client.fetchRegistry: "true"
    #      eureka.client.serviceUrl.defaultZone: http://eurekahost:8761/eureka/
    network_mode: "host"
    tty: true
    build: ./mcem-eureka-server
    image: cloud9/eureka-server
    container_name: "eureka"
    hostname: eurekahost
    volumes:
      - /c9/eureka:/tmp
    privileged: false
    restart: on-failure
  #    depends_on:
  #      - gogs

  outlet:
    ports:
      - 9091:9091/tcp
    environment:
      spring.profiles.active: staging
    network_mode: "host"
    tty: true
    build: ./mcem-outlet-service
    image: cloud9/outlet-service
    container_name: "outlet"
    hostname: outlethost
    volumes:
      - /c9/outlet:/tmp
    privileged: false
    #    extra_hosts:
    #      - "gogshost:35.198.237.22"
    #      - "dbhost:35.198.237.22"
    #      - "miniohost:35.198.237.22"
    #      - "mqhost:192.168.1.102"
    #      - "eurekahost:192.168.1.102"
    #      - "outlethost:192.168.1.102"
    #      - "memberhost:192.168.1.102"
    #      - "campaignhost:192.168.1.102"
    #      - "corehost:192.168.1.102"
    #      - "eventhost:192.168.1.102"
    #      - "uploadhost:192.168.1.102"
    #      - "webhost:192.168.1.102"
    restart: "no"
    depends_on:
      - rabbitmq
#      - eureka

  member:
    ports:
      - 9092:9092/tcp
    environment:
      spring.profiles.active: staging
    network_mode: "host"
    tty: true
    build: ./mcem-member-service
    image: cloud9/member-service
    container_name: "member"
    hostname: memberhost
    volumes:
      - /c9/member:/tmp
    privileged: false
    #    extra_hosts:
    #      - "gogshost:35.198.237.22"
    #      - "dbhost:35.198.237.22"
    #      - "miniohost:35.198.237.22"
    #      - "mqhost:192.168.1.102"
    #      - "eurekahost:192.168.1.102"
    #      - "outlethost:192.168.1.102"
    #      - "memberhost:192.168.1.102"
    #      - "campaignhost:192.168.1.102"
    #      - "corehost:192.168.1.102"
    #      - "eventhost:192.168.1.102"
    #      - "uploadhost:192.168.1.102"
    #      - "webhost:192.168.1.102"
    restart: "no"
    depends_on:
      - rabbitmq
#      - eureka
#      on-failure

  campaign:
    ports:
      - 9093:9093/tcp
    environment:
      spring.profiles.active: staging
    network_mode: "host"
    tty: true
    build: ./mcem-campaign-service
    image: cloud9/campaign-service
    container_name: "campaign"
    hostname: campaignhost
    volumes:
      - /c9/campaign:/tmp
    privileged: false
    #    extra_hosts:
    #      - "gogshost:35.198.237.22"
    #      - "dbhost:35.198.237.22"
    #      - "miniohost:35.198.237.22"
    #      - "mqhost:192.168.1.102"
    #      - "eurekahost:192.168.1.102"
    #      - "outlethost:192.168.1.102"
    #      - "memberhost:192.168.1.102"
    #      - "campaignhost:192.168.1.102"
    #      - "corehost:192.168.1.102"
    #      - "eventhost:192.168.1.102"
    #      - "uploadhost:192.168.1.102"
    #      - "webhost:192.168.1.102"
    restart: "no"
    depends_on:
      - rabbitmq
#      - eureka

  core:
    ports:
      - 9095:9095/tcp
    environment:
      spring.profiles.active: staging
    network_mode: "host"
    tty: true
    build: ./mcem-core-service
    image: cloud9/core-service
    container_name: "core"
    hostname: corehost
    volumes:
      - /c9/core:/tmp
    privileged: false
    #    extra_hosts:
    #      - "gogshost:35.198.237.22"
    #      - "dbhost:35.198.237.22"
    #      - "miniohost:35.198.237.22"
    #      - "mqhost:192.168.1.105"
    #      - "eurekahost:192.168.1.102"
    #      - "outlethost:192.168.1.102"
    #      - "memberhost:192.168.1.102"
    #      - "campaignhost:192.168.1.102"
    #      - "corehost:192.168.1.102"
    #      - "eventhost:192.168.1.102"
    #      - "uploadhost:192.168.1.102"
    #      - "webhost:192.168.1.102"
    restart: "no"
#    depends_on:
#      - rabbitmq
#      - eureka

  event:
    ports:
      - 9096:9096/tcp
    environment:
      spring.profiles.active: staging
    network_mode: "host"
    tty: true
    build: ./mcem-event-service
    image: cloud9/event-service
    container_name: "event"
    hostname: eventhost
    volumes:
      - /c9/event:/tmp
    privileged: false
    #    extra_hosts:
    #      - "gogshost:35.198.237.22"
    #      - "dbhost:35.198.237.22"
    #      - "miniohost:35.198.237.22"
    #      - "mqhost:192.168.1.102"
    #      - "eurekahost:192.168.1.102"
    #      - "outlethost:192.168.1.102"
    #      - "memberhost:192.168.1.102"
    #      - "campaignhost:192.168.1.102"
    #      - "corehost:192.168.1.102"
    #      - "eventhost:192.168.1.102"
    #      - "uploadhost:192.168.1.102"
    #      - "webhost:192.168.1.102"
    restart: "no"
#    depends_on:
#      - rabbitmq
#      - eureka

  upload:
    ports:
      - 9099:9099/tcp
    environment:
      spring.profiles.active: staging
    network_mode: "host"
    tty: true
    build: ./mcem-upload-service
    image: cloud9/upload-service
    container_name: "upload"
    hostname: uploadhost
    volumes:
      - /c9/upload:/tmp
    privileged: false
    #    extra_hosts:
    #      - "gogshost:35.198.237.22"
    #      - "dbhost:35.198.237.22"
    #      - "miniohost:35.198.237.22"
    #      - "mqhost:192.168.1.102"
    #      - "eurekahost:192.168.1.102"
    #      - "outlethost:192.168.1.102"
    #      - "memberhost:192.168.1.102"
    #      - "campaignhost:192.168.1.102"
    #      - "corehost:192.168.1.102"
    #      - "eventhost:192.168.1.102"
    #      - "uploadhost:192.168.1.102"
    #      - "webhost:192.168.1.102"
    restart: "no"
    depends_on:
      - rabbitmq
#      - eureka

  vpn-pos:
    network_mode: "host"
    tty: true
    image: cdrage/openvpn-client
    container_name: "vpn-pos"
    cap_add:
      - NET_ADMIN
    devices:
      - "/dev/net/tun"
    volumes:
      - /vpn-pos/client.ovpn:/etc/openvpn/hacktheplanet.ovpn
      - /vpn-pos/vpn.cert_auth:/etc/openvpn/vpn.cert_auth
    command: hacktheplanet.ovpn
    privileged: false
    restart: on-failure

  gateway:
    ports:
      - 9090:9090/tcp
    environment:
      spring.profiles.active: staging
    network_mode: "host"
    tty: true
    build: ./mcem-gateway-service
    image: cloud9/gateway-service
    container_name: "gateway"
    hostname: gatewayhost
    volumes:
      - /c9/gateway:/tmp
    privileged: false
    #    extra_hosts:
    #      - "gogshost:192.168.108.12"
    #      - "dbhost:192.168.108.12"
    #      - "miniohost:192.168.108.12"
    ##      - "gogshost:35.198.237.22"
    ##      - "dbhost:35.198.237.22"
    ##      - "miniohost:35.198.237.22"
    #      - "mqhost:192.168.1.105"
    #      - "eurekahost:192.168.1.105"
    #      - "outlethost:192.168.1.105"
    #      - "memberhost:192.168.1.105"
    #      - "campaignhost:192.168.1.105"
    #      - "corehost:192.168.1.105"
    #      - "eventhost:192.168.1.105"
    #      - "uploadhost:192.168.1.105"
    #      - "webhost:192.168.1.105"
    restart: "no"
    depends_on:
      #      - mongo
      - rabbitmq
  #      - eureka

  merchant:
    ports:
      - 9094:9094/tcp
    environment:
      spring.profiles.active: staging
    network_mode: "host"
    tty: true
    build: ./mcem-merchant-service
    image: cloud9/merchant-service
    container_name: "merchant"
    hostname: merchanthost
    volumes:
      - /c9/merchant:/tmp
    privileged: false
    #    extra_hosts:
    #      - "gogshost:35.198.237.22"
    #      - "dbhost:35.198.237.22"
    #      - "miniohost:35.198.237.22"
    #      - "mqhost:192.168.1.102"
    #      - "eurekahost:192.168.1.102"
    #      - "outlethost:192.168.1.102"
    #      - "memberhost:192.168.1.102"
    #      - "campaignhost:192.168.1.102"
    #      - "corehost:192.168.1.102"
    #      - "eventhost:192.168.1.102"
    #      - "uploadhost:192.168.1.102"
    #      - "webhost:192.168.1.102"
    restart: "no"
    depends_on:
      #      - mongo
      - rabbitmq
  #      - eureka

  integration:
    ports:
      - 9105:9105/tcp
    environment:
      PROFILE: staging
    network_mode: "host"
    tty: true
    build: ./pos-service
    image: cloud9/integration-service
    container_name: "integration"
    hostname: integrationhost
    volumes:
      - /c9/integration:/tmp
    privileged: false
    #    extra_hosts:
    #      - "gogshost:35.198.237.22"
    #      - "dbhost:35.198.237.22"
    #      - "miniohost:35.198.237.22"
    #      - "mqhost:192.168.1.102"
    #      - "eurekahost:192.168.1.102"
    #      - "outlethost:192.168.1.102"
    #      - "memberhost:192.168.1.102"
    #      - "campaignhost:192.168.1.102"
    #      - "corehost:192.168.1.102"
    #      - "eventhost:192.168.1.102"
    #      - "uploadhost:192.168.1.102"
    #      - "webhost:192.168.1.102"
    restart: "no"
    depends_on:
      #      - mongo
      - rabbitmq
  #      - eureka

  whitelabel:
    ports:
      - 9101:9101/tcp
    environment:
      spring.profiles.active: staging
    network_mode: "host"
    tty: true
    build: ./mcem-whitelabel-service
    image: cloud9/whitelabel-service
    container_name: "whitelabel"
    hostname: wlhost
    volumes:
      - /c9/whitelabel:/tmp
    privileged: false
    #    extra_hosts:
    #      - "gogshost:35.198.237.22"
    #      - "dbhost:35.198.237.22"
    #      - "miniohost:35.198.237.22"
    #      - "mqhost:192.168.1.102"
    #      - "eurekahost:192.168.1.102"
    #      - "outlethost:192.168.1.102"
    #      - "memberhost:192.168.1.102"
    #      - "campaignhost:192.168.1.102"
    #      - "corehost:192.168.1.102"
    #      - "eventhost:192.168.1.102"
    #      - "uploadhost:192.168.1.102"
    #      - "webhost:192.168.1.102"
    restart: "no"
    depends_on:
      #      - mongo
      - rabbitmq
  #      - eureka

  admin-web:
    ports:
      - 9098:9098/tcp
    environment:
      spring.profiles.active: staging
    network_mode: "host"
    tty: true
    build: ./mcem-web
    image: cloud9/admin-web
    hostname: webhost
    container_name: "mcemweb"
    volumes:
      - /c9/web:/tmp
    privileged: false
    #    extra_hosts:
    #      - "gogshost:35.198.237.22"
    #      - "dbhost:35.198.237.22"
    #      - "miniohost:35.198.237.22"
    #      - "mqhost:192.168.1.102"
    #      - "eurekahost:192.168.1.102"
    #      - "outlethost:192.168.1.102"
    #      - "memberhost:192.168.1.102"
    #      - "campaignhost:192.168.1.102"
    #      - "corehost:192.168.1.102"
    #      - "eventhost:192.168.1.102"
    #      - "uploadhost:192.168.1.102"
    #      - "webhost:192.168.1.102"
    restart: "no"
    depends_on:
      - rabbitmq
  #      - eureka

  vpn-client:
    network_mode: "host"
    tty: true
    image: dperson/openvpn-client
    container_name: "vpn-client"
    cap_add:
      - NET_ADMIN
    devices:
      - "/dev/net/tun"
    volumes:
      - /openvpn:/vpn
    privileged: false
    restart: on-failure
